
import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Users,BriefcaseBusiness,IndianRupee,CalendarCheck,LogOut,Menu,RefreshCw,Download,Upload,Edit,Trash2,Save,X,CheckCircle2,Search as SearchIcon}from'lucide-react';
import'./style.css';

const KEY='manpower_local_v6';
const roles=['Frisking','Biometric','Invigilator','Supervisor','System Admin','Runner','Security'];
const shifts=['Shift 1','Shift 2','Full Day'];
const attendanceTypes=['Assigned','Present','Absent','Late','Replaced'];
const sample={staff:[{id:'STF1001',name:'Sathishwaran S',phone:'8940289288',aadhaar:'614607855629',dob:'05-02-2003',location:'Trichy',role:'Biometric',vendorId:'VEN1001',salaryPerShift:1000,bank:'GPay',status:'Active'}],vendors:[{id:'VEN1001',name:'BlueStone Manpower',contact:'Karthi',phone:'9993849490',agreedRate:5000,received:2000}],centers:[{id:'CEN1001',name:'L&T Communication Center',location:'Trichy',contact:'Center Admin',phone:'78788638903',systems:60,bookedSystems:0,image:''}],duties:[{id:'DUT1001',staffId:'STF1001',centerId:'CEN1001',date:new Date().toISOString().slice(0,10),shift:'Shift 1',role:'Biometric',attendance:'Present',salary:900,staffPaid:300,paidDate:'',remarks:'Part Payment',payments:[{amount:300,date:new Date().toISOString().slice(0,10),time:'10:00',mode:'Cash',remarks:'First Pay'}]}]};
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const uid=p=>p+Math.floor(1000+Math.random()*9000);
const titleCase=s=>String(s||'').replace(/\w\S*/g,t=>t.charAt(0).toUpperCase()+t.slice(1).toLowerCase());
function normalize(d){const x={staff:Array.isArray(d?.staff)?d.staff:[],vendors:Array.isArray(d?.vendors)?d.vendors:[],centers:Array.isArray(d?.centers)?d.centers:[],duties:Array.isArray(d?.duties)?d.duties:[]};x.staff=x.staff.map(s=>({aadhaar:'',dob:'',location:'',bank:'',status:'Active',...s}));x.vendors=x.vendors.map(v=>({agreedRate:0,received:0,...v}));x.centers=x.centers.map(c=>({systems:0,bookedSystems:0,image:'',...c}));x.duties=x.duties.map(d=>{const ps=Array.isArray(d.payments)?d.payments:[];const paid=ps.reduce((a,b)=>a+Number(b.amount||0),0)||Number(d.staffPaid||0);return{paidDate:'',remarks:'',bookedSystems:0,...d,payments:ps,staffPaid:paid}});return x}
function load(){try{for(const k of[KEY,'manpower_local_v5','manpower_frontend_only_v4','manpower_frontend_only_v3','manpower_frontend_only_v2','manpower_frontend_only_v1']){const r=localStorage.getItem(k);if(r)return normalize(JSON.parse(r))}return normalize(sample)}catch{return normalize(sample)}}
function blob(name,content,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++}else if(c=='"')q=!q;else if(c==','&&!q){row.push(cell.trim());cell=''}else if((c=='\n'||c=='\r')&&!q){if(cell||row.length){row.push(cell.trim());rows.push(row);row=[];cell=''}if(c=='\r'&&n=='\n')i++}else cell+=c}if(cell||row.length){row.push(cell.trim());rows.push(row)}if(!rows.length)return[];const h=rows[0].map(x=>x.toLowerCase().replace(/\s+/g,''));return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])))}

function App(){
 const [data,setData]=useState(load),[tab,setTab]=useState('dashboard'),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[staffSearch,setStaffSearch]=useState(''),[salaryFilter,setSalaryFilter]=useState('all'),[editing,setEditing]=useState(null),[showHistory,setShowHistory]=useState('');
 const blankStaff={name:'',phone:'',aadhaar:'',dob:'',location:'',role:'Frisking',vendorId:'',salaryPerShift:'',bank:'',status:'Active'},blankVendor={name:'',contact:'',phone:'',agreedRate:'',received:'0'},blankCenter={name:'',location:'',contact:'',phone:'',systems:'',bookedSystems:'',image:''},blankDuty={staffId:'',centerId:'',date:today(),shift:'Shift 1',attendance:'Assigned',salary:'',staffPaid:'0',paidDate:'',remarks:'',bookedSystems:'',payments:[]};
 const [staffForm,setStaffForm]=useState(blankStaff),[vendorForm,setVendorForm]=useState(blankVendor),[centerForm,setCenterForm]=useState(blankCenter),[dutyForm,setDutyForm]=useState(blankDuty),[payForm,setPayForm]=useState({dutyId:'',amount:'',date:today(),time:nowTime(),mode:'Cash',remarks:''});
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data]);
 const maps=useMemo(()=>({staff:Object.fromEntries(data.staff.map(x=>[x.id,x])),vendors:Object.fromEntries(data.vendors.map(x=>[x.id,x])),centers:Object.fromEntries(data.centers.map(x=>[x.id,x]))}),[data]);
 const duties=data.duties.map(d=>{const staff=maps.staff[d.staffId],vendor=staff?maps.vendors[staff.vendorId]:null,center=maps.centers[d.centerId],payments=Array.isArray(d.payments)?d.payments:[],paid=payments.reduce((s,p)=>s+Number(p.amount||0),0)||Number(d.staffPaid||0),salary=Number(d.salary||0);return{...d,staff,vendor,center,payments,staffPaid:paid,salary,staffPending:salary-paid}});
 const dashboardText=d=>`${d.date} ${d.staff?.name||''} ${d.staff?.phone||''} ${d.staff?.aadhaar||''} ${d.staff?.location||''} ${d.vendor?.name||''} ${d.center?.name||''} ${d.role} ${d.shift}`.toLowerCase();
 const filteredDuties=duties.filter(d=>dashboardText(d).includes(query.toLowerCase()));
 const filteredStaff=data.staff.filter(s=>`${s.name} ${s.phone} ${s.aadhaar} ${s.dob} ${s.location} ${s.role} ${maps.vendors[s.vendorId]?.name||''}`.toLowerCase().includes(staffSearch.toLowerCase()));
 const salaryDuties=filteredDuties.filter(d=>salaryFilter==='paid'?d.staffPending<=0:salaryFilter==='pending'?d.staffPaid<=0:salaryFilter==='partial'?d.staffPaid>0&&d.staffPending>0:true);
 const vendorSummary=data.vendors.map(v=>{const vd=duties.filter(d=>d.vendor?.id===v.id),staffSalaryTotal=vd.reduce((s,d)=>s+d.salary,0),staffPaid=vd.reduce((s,d)=>s+d.staffPaid,0),agreedAmount=Number(v.agreedRate||0),received=Number(v.received||0);return{...v,agreedAmount,received,vendorPending:agreedAmount-received,staffSalaryTotal,staffPaid,staffPending:staffSalaryTotal-staffPaid}});
 const stats={staff:data.staff.length,todayDuty:duties.filter(d=>d.date===today()).length,totalSalary:duties.reduce((s,d)=>s+d.salary,0),staffPaid:duties.reduce((s,d)=>s+d.staffPaid,0),staffPending:duties.reduce((s,d)=>s+d.staffPending,0),vendorPending:vendorSummary.reduce((s,v)=>s+Number(v.vendorPending||0),0)};
 function refresh(){setData(load());alert('Data Refreshed')}
 function cancel(){setEditing(null);setStaffForm(blankStaff);setVendorForm(blankVendor);setCenterForm(blankCenter);setDutyForm(blankDuty)}
 function remove(type,id){if(confirm('Delete This Record?'))setData(p=>({...p,[type]:p[type].filter(x=>x.id!==id)}))}
 function edit(type,item){setEditing({type,id:item.id}); if(type==='staff')setStaffForm({...blankStaff,...item}); if(type==='vendors')setVendorForm({...blankVendor,...item}); if(type==='centers')setCenterForm({...blankCenter,...item}); if(type==='duties')setDutyForm({...blankDuty,...item,staffPaid:String(item.staffPaid||0),salary:String(item.salary||0)})}
 function upsert(type,item){setData(p=>{const ex=p[type].some(x=>x.id===item.id);return{...p,[type]:ex?p[type].map(x=>x.id===item.id?item:x):[...p[type],item]}});cancel()}
 function addStaff(e){e.preventDefault();if(!staffForm.name||!staffForm.phone)return alert('Enter Staff Name And Phone');upsert('staff',{...staffForm,name:titleCase(staffForm.name),location:titleCase(staffForm.location),id:staffForm.id||uid('STF'),salaryPerShift:Number(staffForm.salaryPerShift||0)})}
 function addVendor(e){e.preventDefault();if(!vendorForm.name)return alert('Enter Vendor Name');upsert('vendors',{...vendorForm,name:titleCase(vendorForm.name),contact:titleCase(vendorForm.contact),id:vendorForm.id||uid('VEN'),agreedRate:Number(vendorForm.agreedRate||0),received:Number(vendorForm.received||0)})}
 function addCenter(e){e.preventDefault();if(!centerForm.name||!centerForm.location)return alert('Enter Center Name And Location');upsert('centers',{...centerForm,name:titleCase(centerForm.name),location:titleCase(centerForm.location),contact:titleCase(centerForm.contact),id:centerForm.id||uid('CEN'),systems:Number(centerForm.systems||0),bookedSystems:Number(centerForm.bookedSystems||0)})}
 function centerImageUpload(e){const file=e.target.files?.[0];if(!file)return;if(file.size>900000)return alert('Image Size Must Be Below 900KB');const reader=new FileReader();reader.onload=()=>setCenterForm({...centerForm,image:reader.result});reader.readAsDataURL(file)}
 function addDuty(e){e.preventDefault();const st=maps.staff[dutyForm.staffId];if(!st||!dutyForm.centerId)return alert('Select Staff And Center');const salary=Number(dutyForm.salary||st.salaryPerShift||0),paid=Number(dutyForm.staffPaid||0);let payments=Array.isArray(dutyForm.payments)?[...dutyForm.payments]:[];const existingPaid=payments.reduce((sum,p)=>sum+Number(p.amount||0),0);if(paid!==existingPaid){payments=paid>0?[{amount:paid,date:dutyForm.paidDate||today(),time:nowTime(),mode:'Cash',remarks:editing?.type==='duties'?'Manual Update':'Opening Payment'}]:[]}const item={...dutyForm,id:dutyForm.id||uid('DUT'),role:st.role,salary,staffPaid:payments.reduce((sum,p)=>sum+Number(p.amount||0),0),bookedSystems:Number(dutyForm.bookedSystems||0),paidDate:payments.reduce((sum,p)=>sum+Number(p.amount||0),0)>=salary&&salary>0?(dutyForm.paidDate||today()):'',payments};upsert('duties',item)}
 function fullSalaryPay(id){setData(p=>({...p,duties:p.duties.map(d=>{if(d.id!==id)return d;const paid=(d.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0),bal=Number(d.salary||0)-paid;if(bal<=0)return d;const payments=[...(d.payments||[]),{amount:bal,date:today(),time:nowTime(),mode:'Cash',remarks:'Full Pay'}];return{...d,payments,staffPaid:Number(d.salary||0),paidDate:today(),remarks:d.remarks?d.remarks+' | Full Salary Paid':'Full Paid'}})}))}
 function addPartPayment(e){e.preventDefault();if(!payForm.dutyId||!payForm.amount)return alert('Select Duty And Enter Amount');setData(p=>({...p,duties:p.duties.map(d=>{if(d.id!==payForm.dutyId)return d;const payments=[...(d.payments||[]),{amount:Number(payForm.amount),date:payForm.date,time:payForm.time,mode:payForm.mode,remarks:payForm.remarks}],total=payments.reduce((s,x)=>s+Number(x.amount||0),0);return{...d,payments,staffPaid:total,paidDate:total>=Number(d.salary||0)?payForm.date:d.paidDate,remarks:payForm.remarks||d.remarks}})}));setPayForm({dutyId:'',amount:'',date:today(),time:nowTime(),mode:'Cash',remarks:''})}
 async function bulk(type,e){const file=e.target.files?.[0];if(!file)return;const rows=parseCSV(await file.text());if(!rows.length)return alert('CSV Empty Or Invalid');if(type==='staff'){const arr=rows.map(r=>{const v=data.vendors.find(x=>x.name.toLowerCase()===String(r.vendor||r.vendorname||'').toLowerCase());return{id:r.id||uid('STF'),name:titleCase(r.name||r.staff||r.staffname),phone:r.phone||'',aadhaar:r.aadhaar||r.aadhaarnumber||'',dob:r.dob||'',location:titleCase(r.location||''),role:r.role||'Frisking',vendorId:v?.id||r.vendorid||'',salaryPerShift:Number(r.salarypershift||r.salary||0),bank:r.bank||r.upi||'',status:r.status||'Active'}}).filter(x=>x.name);setData(p=>({...p,staff:[...p.staff,...arr]}));alert(arr.length+' Staff Added')}if(type==='vendors'){const arr=rows.map(r=>({id:r.id||uid('VEN'),name:titleCase(r.name||r.vendor||r.vendorname),contact:titleCase(r.contact||r.contactperson),phone:r.phone||'',agreedRate:Number(r.agreedamount||r.agreedrate||r.amount||0),received:Number(r.received||r.receivedamount||0)})).filter(x=>x.name);setData(p=>({...p,vendors:[...p.vendors,...arr]}));alert(arr.length+' Vendors Added')}if(type==='centers'){const arr=rows.map(r=>({id:r.id||uid('CEN'),name:titleCase(r.name||r.center||r.centername),location:titleCase(r.location),contact:titleCase(r.contact||r.contactperson),phone:r.phone||'',systems:Number(r.systems||r.systemcount||r.totalsystems||0)})).filter(x=>x.name);setData(p=>({...p,centers:[...p.centers,...arr]}));alert(arr.length+' Centers Added')}e.target.value=''}
 function sampleCSV(type){const s={staff:'name,phone,aadhaar,dob,location,role,vendor,salaryPerShift,bank,status\nSathishwaran,8940289288,123456789012,2000-01-01,Trichy,Biometric,BlueStone Manpower,900,GPay,Active',vendors:'name,contact,phone,agreedAmount,received\nBlueStone Manpower,Ramesh,9000011111,5000,2000',centers:'name,location,contact,phone,systems\nL&T Communication Center,Trichy,Center Admin,9111122222,60'};blob(type+'-sample.csv',s[type],'text/csv')}
 function exportBackup(){blob('manpower-backup-'+today()+'.json',JSON.stringify(data,null,2),'application/json')}
 async function restoreBackup(e){const f=e.target.files?.[0];if(!f)return;try{setData(normalize(JSON.parse(await f.text())));alert('Backup Restored Successfully')}catch{alert('Invalid Backup File')}e.target.value=''}
 function dutyCSV(){blob('duty-report-'+today()+'.csv',csv([['Date','Staff','Phone','Aadhaar','DOB','Staff Location','Vendor','Center','Total Systems','Booked Systems','Available Systems','Role','Shift','Attendance','Salary','Salary Paid','Salary Pending','Paid Date','Payment History','Remarks'],...duties.map(d=>[d.date,d.staff?.name,d.staff?.phone,d.staff?.aadhaar,d.staff?.dob,d.staff?.location,d.vendor?.name,d.center?.name,d.center?.systems,d.bookedSystems||0,Math.max(Number(d.center?.systems||0)-Number(d.bookedSystems||0),0),d.role,d.shift,d.attendance,d.salary,d.staffPaid,d.staffPending,d.paidDate,(d.payments||[]).map(p=>`${p.date} ${p.time} ${money(p.amount)} ${p.mode} ${p.remarks||''}`).join(' | '),d.remarks])]),'text/csv')}
 function staffCSV(){blob('staff-report-'+today()+'.csv',csv([['Name','Phone','Aadhaar','DOB','Location','Role','Vendor','Salary Per Shift','Bank / UPI','Status'],...data.staff.map(s=>[s.name,s.phone,s.aadhaar,s.dob,s.location,s.role,maps.vendors[s.vendorId]?.name||'Direct',s.salaryPerShift,s.bank,s.status])]),'text/csv')}
 function vendorCSV(){blob('vendor-pending-report-'+today()+'.csv',csv([['Vendor','Contact Person','Phone','Agreed Amount','Received From Vendor','Vendor Pending','Staff Salary Total','Staff Paid','Staff Pending'],...vendorSummary.map(v=>[v.name,v.contact,v.phone,v.agreedAmount,v.received,v.vendorPending,v.staffSalaryTotal,v.staffPaid,v.staffPending])]),'text/csv')}
 function centerCSV(){blob('center-report-'+today()+'.csv',csv([['Center','Location','Contact Person','Phone','Total Systems','Booked Systems','Available Systems'],...data.centers.map(c=>[c.name,c.location,c.contact,c.phone,c.systems||0,c.bookedSystems||0,Math.max(Number(c.systems||0)-Number(c.bookedSystems||0),0)])]),'text/csv')}
 const nav=['dashboard','duty','staff','vendors','centers','salary','backup'];
 return <div className="appShell">{open&&<button className="overlay" onClick={()=>setOpen(false)}>×</button>}<aside className={'sidebar '+(open?'open':'')}><div className="brand"><div className="logo">SB</div><div><strong>Infotech Solutions</strong><span>Manpower Management</span></div></div><nav>{nav.map(n=><button key={n} className={tab===n?'active':''} onClick={()=>{setTab(n);setOpen(false)}}>{n}</button>)}</nav><button className="logout" onClick={()=>alert('Frontend-Only Local App. No Backend Needed.')}><LogOut size={17}/> Logout</button></aside><main className="main"><section className="hero"><div><button className="menuBtn" onClick={()=>setOpen(true)}><Menu size={18}/></button><p className="eyebrow">Workforce Control Panel</p><h1>SB Infotech Manpower Management</h1><p className="sub">Tiruchirapalli, TamilNadu, 620008.</p></div><button className="refresh" onClick={refresh}><RefreshCw size={17}/> Refresh</button></section><div className="space">
 {tab==='dashboard'&&<><SearchBox cls="dashboardSearch" query={query} setQuery={setQuery} placeholder="Search Dashboard By Staff, Vendor, Center, Aadhaar, Location, Date..." /><div className="cards"><Stat icon={Users} title="Total Staff" value={stats.staff}/><Stat icon={CalendarCheck} title="Today Duty" value={stats.todayDuty}/><Stat icon={IndianRupee} title="Salary Pending" value={money(stats.staffPending)} warn/><Stat icon={BriefcaseBusiness} title="Vendor Pending" value={money(stats.vendorPending)} warn/></div><div className="twoCol"><Panel title="Recent Duties"><DutyTable duties={filteredDuties.slice(0,8)} edit={edit} remove={remove} fullSalaryPay={fullSalaryPay} showHistory={showHistory} setShowHistory={setShowHistory}/></Panel><Panel title="Vendor Pending"><div className="vendorSummaryBox">{vendorSummary.map(v=><div className="miniCard" key={v.id}><div className="vendorSummaryDetails"><b>{v.name}</b><small>Agreed: {money(v.agreedAmount)}</small><small>Received: {money(v.received)}</small></div><span className="vendorAmount">{money(v.vendorPending)}</span></div>)}</div></Panel></div></>}
 {tab==='duty'&&<Panel title="Duty Assignment"><form onSubmit={addDuty} className="formGrid"><Field type="select" label="Staff" value={dutyForm.staffId} onChange={v=>{const s=maps.staff[v];setDutyForm({...dutyForm,staffId:v,salary:s?.salaryPerShift||''})}} options={[['','Select Staff'],...data.staff.map(s=>[s.id,`${s.name} - ${s.role}`])]}/><Field type="select" label="Center" value={dutyForm.centerId} onChange={v=>setDutyForm({...dutyForm,centerId:v})} options={[['','Select Center'],...data.centers.map(c=>[c.id,`${c.name} (${c.systems||0} Systems)`])]}/><Field label="Date" inputType="date" value={dutyForm.date} onChange={v=>setDutyForm({...dutyForm,date:v})}/><Field type="select" label="Shift" value={dutyForm.shift} onChange={v=>setDutyForm({...dutyForm,shift:v})} options={shifts.map(x=>[x,x])}/><Field type="select" label="Attendance" value={dutyForm.attendance} onChange={v=>setDutyForm({...dutyForm,attendance:v})} options={attendanceTypes.map(x=>[x,x])}/><Field label="Salary" inputType="number" value={dutyForm.salary} onChange={v=>setDutyForm({...dutyForm,salary:v})}/><Field label="Salary Paid" inputType="number" value={dutyForm.staffPaid} onChange={v=>setDutyForm({...dutyForm,staffPaid:v})}/><Field label="Remarks" value={dutyForm.remarks} onChange={v=>setDutyForm({...dutyForm,remarks:v})}/><button className="primary"><Save size={16}/>{editing?.type==='duties'?'Update Duty':'Add Duty'}</button>{editing?.type==='duties'&&<button type="button" className="small" onClick={cancel}><X size={16}/>Cancel</button>}</form><SearchBox query={query} setQuery={setQuery}/><DutyTable duties={filteredDuties} edit={edit} remove={remove} fullSalaryPay={fullSalaryPay} showHistory={showHistory} setShowHistory={setShowHistory}/></Panel>}
 {tab==='staff'&&<Panel title="Staff Management"><div className="filterRow"><label className="primary uploadLabel"><Upload size={16}/> Bulk Upload Staff CSV<input className="fileInput" type="file" accept=".csv" onChange={e=>bulk('staff',e)}/></label><button className="small" onClick={()=>sampleCSV('staff')}><Download size={15}/> Sample Staff CSV</button><button className="small" onClick={staffCSV}><Download size={15}/> Staff CSV Report</button></div><form onSubmit={addStaff} className="formGrid"><Field label="Name" value={staffForm.name} onChange={v=>setStaffForm({...staffForm,name:v})}/><Field label="Phone" value={staffForm.phone} onChange={v=>setStaffForm({...staffForm,phone:v})}/><Field label="Aadhaar Number" value={staffForm.aadhaar} onChange={v=>setStaffForm({...staffForm,aadhaar:v})}/><Field label="DOB" inputType="date" value={staffForm.dob} onChange={v=>setStaffForm({...staffForm,dob:v})}/><Field label="Location" value={staffForm.location} onChange={v=>setStaffForm({...staffForm,location:v})}/><Field type="select" label="Role" value={staffForm.role} onChange={v=>setStaffForm({...staffForm,role:v})} options={roles.map(x=>[x,x])}/><Field type="select" label="Vendor" value={staffForm.vendorId} onChange={v=>setStaffForm({...staffForm,vendorId:v})} options={[['','Direct'],...data.vendors.map(v=>[v.id,v.name])]}/><Field label="Salary / Shift" inputType="number" value={staffForm.salaryPerShift} onChange={v=>setStaffForm({...staffForm,salaryPerShift:v})}/><Field label="Bank / UPI" value={staffForm.bank} onChange={v=>setStaffForm({...staffForm,bank:v})}/><button className="primary"><Save size={16}/>{editing?.type==='staff'?'Update Staff':'Add Staff'}</button>{editing?.type==='duties'&&<button type="button" className="small" onClick={cancel}><X size={16}/>Cancel</button>}</form><SearchBox query={staffSearch} setQuery={setStaffSearch} placeholder="Search Staff By Name, Phone, Aadhaar, Location, Role..." /><div className="gridCards">{filteredStaff.map(s=><Info key={s.id} title={s.name} lines={[s.role,s.phone,`Aadhaar: ${s.aadhaar||'-'}`,`DOB: ${s.dob||'-'}`,`Location: ${s.location||'-'}`,maps.vendors[s.vendorId]?.name||'Direct',money(s.salaryPerShift)+'/Shift']} onEdit={()=>edit('staff',s)} onDelete={()=>remove('staff',s.id)}/>)}</div></Panel>}
 {tab==='vendors'&&<Panel title="Vendor Management"><div className="filterRow"><label className="primary uploadLabel"><Upload size={16}/> Bulk Upload Vendor CSV<input className="fileInput" type="file" accept=".csv" onChange={e=>bulk('vendors',e)}/></label><button className="small" onClick={()=>sampleCSV('vendors')}><Download size={15}/> Sample Vendor CSV</button></div><form onSubmit={addVendor} className="formGrid"><Field label="Vendor Name" value={vendorForm.name} onChange={v=>setVendorForm({...vendorForm,name:v})}/><Field label="Contact Person" value={vendorForm.contact} onChange={v=>setVendorForm({...vendorForm,contact:v})}/><Field label="Phone" value={vendorForm.phone} onChange={v=>setVendorForm({...vendorForm,phone:v})}/><Field label="Agreed Amount" inputType="number" value={vendorForm.agreedRate} onChange={v=>setVendorForm({...vendorForm,agreedRate:v})}/><Field label="Received From Vendor" inputType="number" value={vendorForm.received} onChange={v=>setVendorForm({...vendorForm,received:v})}/><button className="primary"><Save size={16}/>{editing?.type==='vendors'?'Update Vendor':'Add Vendor'}</button>{editing&&<button type="button" className="small" onClick={cancel}><X size={16}/>Cancel</button>}</form><div className="gridCards">{vendorSummary.map(v=><Info key={v.id} title={v.name} lines={[`Contact Person: ${v.contact}`,v.phone,`Agreed: ${money(v.agreedAmount)}`,`Received: ${money(v.received)}`,`Vendor Pending: ${money(v.vendorPending)}`,`Staff Salary Total: ${money(v.staffSalaryTotal)}`]} onEdit={()=>edit('vendors',v)} onDelete={()=>remove('vendors',v.id)}/>)}</div></Panel>}
 {tab==='centers'&&<Panel title="Center Management"><div className="filterRow"><label className="primary uploadLabel"><Upload size={16}/> Bulk Upload Center CSV<input className="fileInput" type="file" accept=".csv" onChange={e=>bulk('centers',e)}/></label><button className="small" onClick={()=>sampleCSV('centers')}><Download size={15}/> Sample Center CSV</button><button className="small" onClick={centerCSV}><Download size={15}/> Center CSV Report</button></div><form onSubmit={addCenter} className="formGrid"><Field label="Center Name" value={centerForm.name} onChange={v=>setCenterForm({...centerForm,name:v})}/><Field label="Location" value={centerForm.location} onChange={v=>setCenterForm({...centerForm,location:v})}/><Field label="Contact Person" value={centerForm.contact} onChange={v=>setCenterForm({...centerForm,contact:v})}/><Field label="Phone" value={centerForm.phone} onChange={v=>setCenterForm({...centerForm,phone:v})}/><Field label="Total Systems" inputType="number" value={centerForm.systems} onChange={v=>setCenterForm({...centerForm,systems:v})}/><Field label="Booked Systems" inputType="number" value={centerForm.bookedSystems} onChange={v=>setCenterForm({...centerForm,bookedSystems:v})}/><label><span>Center Image</span><input type="file" accept="image/*" onChange={centerImageUpload}/></label><button className="primary"><Save size={16}/>{editing?.type==='centers'?'Update Center':'Add Center'}</button>{editing?.type==='centers'&&<button type="button" className="small" onClick={cancel}><X size={16}/>Cancel</button>}</form><div className="gridCards">{data.centers.map(c=><Info key={c.id} image={c.image} title={c.name} lines={[c.location,`Contact Person: ${c.contact}`,c.phone,`Total Systems: ${c.systems||0}`,`Booked Systems: ${c.bookedSystems||0}`,`Available Systems: ${Math.max(Number(c.systems||0)-Number(c.bookedSystems||0),0)}`]} onEdit={()=>edit('centers',c)} onDelete={()=>remove('centers',c.id)}/>)}</div></Panel>}
 {tab==='salary'&&<Panel title="Salary Pay & Pending"><div className="cards"><Stat icon={IndianRupee} title="Total Staff Salary" value={money(stats.totalSalary)}/><Stat icon={CheckCircle2} title="Salary Paid" value={money(stats.staffPaid)} good/><Stat icon={IndianRupee} title="Salary Pending" value={money(stats.staffPending)} warn/><Stat icon={BriefcaseBusiness} title="Vendor Pending" value={money(stats.vendorPending)} warn/></div><form onSubmit={addPartPayment} className="formGrid"><Field type="select" label="Select Staff Duty" value={payForm.dutyId} onChange={v=>setPayForm({...payForm,dutyId:v})} options={[['','Select Duty'],...duties.map(d=>[d.id,`${d.staff?.name||'Unknown'} - ${d.date} - Pending ${money(d.staffPending)}`])]}/><Field label="Part Payment Amount" inputType="number" value={payForm.amount} onChange={v=>setPayForm({...payForm,amount:v})}/><Field label="Payment Date" inputType="date" value={payForm.date} onChange={v=>setPayForm({...payForm,date:v})}/><Field label="Payment Time" inputType="time" value={payForm.time} onChange={v=>setPayForm({...payForm,time:v})}/><Field type="select" label="Payment Mode" value={payForm.mode} onChange={v=>setPayForm({...payForm,mode:v})} options={[['Cash','Cash'],['GPay','GPay'],['UPI','UPI'],['Bank','Bank']]}/><Field label="Remarks" value={payForm.remarks} onChange={v=>setPayForm({...payForm,remarks:v})}/><button className="primary"><Save size={16}/>Add Part Payment</button></form><div className="filterRow">{['all','paid','pending','partial'].map(f=><button key={f} className={'small '+(salaryFilter===f?'active':'')} onClick={()=>setSalaryFilter(f)}>{titleCase(f)}</button>)}</div><SearchBox query={query} setQuery={setQuery}/><DutyTable duties={salaryDuties} edit={edit} remove={remove} fullSalaryPay={fullSalaryPay} showHistory={showHistory} setShowHistory={setShowHistory}/></Panel>}
 {tab==='backup'&&<Panel title="Backup, Restore & Reports"><div className="backupGrid"><button className="primary" onClick={exportBackup}><Download size={17}/>Full JSON Backup</button><label className="primary uploadLabel"><Upload size={17}/>Restore JSON Backup<input className="fileInput" type="file" accept=".json" onChange={restoreBackup}/></label><button className="primary" onClick={dutyCSV}><Download size={17}/>Duty CSV Report</button><button className="primary" onClick={staffCSV}><Download size={17}/>Staff CSV Report</button><button className="primary" onClick={vendorCSV}><Download size={17}/>Vendor Pending CSV</button><button className="primary" onClick={centerCSV}><Download size={17}/>Center CSV Report</button></div><p className="sub" style={{color:'#64748b',marginTop:14}}>JSON Is For Full Backup/Restore. CSV Is For Excel Reports And Bulk Upload Templates.</p></Panel>}
 </div><footer className="appFooter"><div><strong>Developed By Sathishwaran Sasikumar</strong><span>Tiruchirapalli, TamilNadu · ssathishwaran62@gmail.com +91 8940289288</span></div><div>© 2026 Sathishwaran Sasikumar All Rights Reserved</div></footer></main></div>
}
function Stat({icon:Icon,title,value,good,warn}){return <div className={'statCard '+(good?'good ':'')+(warn?'warn':'')}><Icon/><div><p>{title}</p><h2>{value}</h2></div></div>}
function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Field({label,value,onChange,type,inputType='text',options=[]}){return <label><span>{label}</span>{type==='select'?<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>:<input type={inputType} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function SearchBox({query,setQuery,placeholder='Search Staff, Aadhaar, Location, Vendor, Center, Date...',cls=''}){return <div className={'search '+cls}><SearchIcon size={18}/><input placeholder={placeholder} value={query} onChange={e=>setQuery(e.target.value)}/></div>}
function Info({title,lines,onEdit,onDelete,image}){return <div className="infoCard">{image&&<img className="centerImage" src={image} alt={title}/>}<h3>{title}</h3>{lines.map((l,i)=><p key={i}>{l}</p>)}<div className="actionRow" style={{marginTop:12}}><button className="small" onClick={onEdit}><Edit size={14}/>Edit</button><button className="small" onClick={onDelete}><Trash2 size={14}/>Delete</button></div></div>}
function DutyTable({duties,edit,remove,fullSalaryPay,showHistory,setShowHistory}){return <div className="tableWrap"><table><thead><tr><th>Date</th><th>Staff</th><th>Center</th><th>Vendor</th><th>Role / Shift</th><th>Attendance</th><th>Salary</th><th>Paid</th><th>Pending</th><th>Action</th></tr></thead><tbody>{duties.length===0&&<tr><td colSpan="10" className="empty">No Records Found</td></tr>}{duties.map(d=><tr key={d.id}><td>{d.date}</td><td><button className="nameLink" onClick={()=>setShowHistory(showHistory===d.id?'':d.id)}>{d.staff?.name||'Unknown'}</button><small>{d.staff?.phone||''}</small><small>{d.staff?.location||''}</small>{showHistory===d.id&&<div className="historyBox">{d.payments?.length?d.payments.map((p,i)=><p key={i}>{p.date} {p.time} - {money(p.amount)} - {p.mode} {p.remarks?`(${p.remarks})`:''}</p>):<p>No Payment History</p>}</div>}</td><td>{d.center?.name||''}<small>{d.center?.location||''}</small><small>Total Systems: {d.center?.systems||0}</small><small>Booked: {d.bookedSystems||0}</small><small>Available: {Math.max(Number(d.center?.systems||0)-Number(d.bookedSystems||0),0)}</small></td><td>{d.vendor?.name||'Direct'}</td><td>{d.role}<small>{d.shift}</small></td><td><span className="badge neutral">{d.attendance}</span></td><td>{money(d.salary)}</td><td>{money(d.staffPaid)}<small>{d.paidDate?'Paid: '+d.paidDate:''}</small></td><td><span className={'badge '+(d.staffPending<=0?'paid':d.staffPaid>0?'neutral':'pending')}>{money(d.staffPending)}</span></td><td><div className="actionRow">{d.staffPending>0&&<button className="small payBtn" onClick={()=>fullSalaryPay(d.id)}>Full Pay</button>}<button className="small" onClick={()=>edit('duties',d)}><Edit size={14}/></button><button className="small" onClick={()=>remove('duties',d.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>}
createRoot(document.getElementById('root')).render(<App/>);
